// Code generated by hertz generator.

package blog

import (
	"Blog/dao/mysql"
	"Blog/dao/redis"
	"Blog/utils"
	"context"
	"fmt"
	"strconv"

	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createblogMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createblog0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createblog1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _passwordloginMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _passwordlogin0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _passwordlogin1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _register0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _register1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _loginMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		func(c context.Context, ctx *app.RequestContext) {
			token := string(ctx.GetHeader("Authorization"))
			userid, err := utils.ParseToken(token)
			if err != nil {
				json := make(map[string]interface{})
				json["status_code"] = 2001
				json["status_msg"] = "登录过期"
				json["data"] = nil
				ctx.AbortWithStatusJSON(200, json)
			} else {
				redisToken, err := redis.GetToken(userid)
				if err != nil {
					fmt.Println(err)
					json := make(map[string]interface{})
					json["status_code"] = 2001
					json["status_msg"] = "登录过期"
					json["data"] = nil
					ctx.AbortWithStatusJSON(200, json)
				} else {
					if token != redisToken {
						json := make(map[string]interface{})
						json["status_code"] = 2002
						json["status_msg"] = "异地登陆"
						json["data"] = nil
						ctx.AbortWithStatusJSON(200, json)
					} else {
						ctx.Set("userid", strconv.FormatInt(userid, 10))
						ctx.Next(c)
					}
				}
			}
		},
	}
}

func _unloginMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		func(c context.Context, ctx *app.RequestContext) {
			token := string(ctx.GetHeader("Authorization"))
			userid, err := utils.ParseToken(token)
			if err != nil {
				ctx.Set("isLogin", "false")
			} else {
				redisToken, err := redis.GetToken(userid)
				if token != redisToken || err != nil {
					ctx.Set("isLogin", "false")
				} else {
					ctx.Set("userid", strconv.FormatInt(userid, 10))
					ctx.Set("isLogin", "true")
				}
			}
			ctx.Next(c)
		},
	}
}

func _getblogbytypeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getblogbytype0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getblogbytype1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getblogbykeywordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getblogbykeyword0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getblogbykeyword1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _adminMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{
		func(c context.Context, ctx *app.RequestContext) {
			userid, _ := strconv.Atoi(ctx.GetString("userid"))
			status, _ := mysql.GetUserStatus(userid)
			if status != 1 {
				json := make(map[string]interface{})
				json["status_code"] = 2003
				json["status_msg"] = "无权访问"
				json["data"] = nil
				ctx.AbortWithStatusJSON(200, json)
			}
		},
	}
	return nil
}

func _getpendingMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getpending0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getpending1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _approbalblogMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _approvalblogMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _approvalblog0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _logoutMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _logout0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _logout1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _forbiddenuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _forbiddenuser0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _forbiddenuser1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getforbiddenMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getforbidden0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getforbidden1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _uploadMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _upload0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _upload1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _likeblogMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _likeblog0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _likeblog1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _favorblogMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _favorblog0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _favorblog1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getfavorMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getfaborMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getfabor0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getfavor0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getfavor1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserbykeywordMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserbykeyword0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserbykeyword1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _followuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _followuser0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _followuser1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getfollowMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getfollow0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getfollow1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _commentblogMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _commentblog0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _commentblog1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getblogcommentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getblogcomment0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getblogcomment1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getdraftMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getdraft0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserblogMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserblog0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserblog1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _changeuserinfoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _changeuserinfo0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _changedraftMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _chengedraftMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _recommentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _recomment0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getrecommentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getrecomment0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getrecomment1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _likecommentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _likecomment0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gethotblogMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gethotblog0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _gethotblog1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getalltypeMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getalltype0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getalltype1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addannouncementMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addannouncement0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _addannouncement1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getannouncementMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getannouncement0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getannouncement1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _delannouncementMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _delannouncement0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _delannouncement1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getblogbyidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getblogbyid0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getblogbyid1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _delblogMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _delblog0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserbyidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserinfobyidMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getuserinfobyid0Mw() []app.HandlerFunc {
	// your code...
	return nil
}
